on:
  pull_request:
  push:
    branches:
      - main
      - "patch-release-*"

name: continuous-integration

env:
  NUSHELL_CARGO_PROFILE: ci
  NU_LOG_LEVEL: DEBUG
  # If changing these settings also change toolkit.nu
  CLIPPY_OPTIONS: "-D warnings -D clippy::unwrap_used -D clippy::unchecked_duration_subtraction"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  std-lib-and-python-virtualenv:
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-22.04, macos-latest, windows-latest]
        py:
          - py

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.12.0

      - name: Install Nushell
        run: cargo install --path . --locked --force

      - name: Upload Nushell build (Ubuntu and macOS)
        uses: actions/upload-artifact@v6
        if: runner.os != 'Windows'
        with:
          name: "nu-${{ github.event.number || github.ref_name }}-${{ matrix.platform }}"
          path: "~/.cargo/bin/nu"
          retention-days: 14

      - name: Upload Nushell build (Windows)
        uses: actions/upload-artifact@v6
        if: runner.os == 'Windows'
        with:
          name: "nu-${{ github.event.number || github.ref_name }}-${{ matrix.platform }}"
          path: 'C:\Users\runneradmin\.cargo\bin\nu.exe'
          retention-days: 14

      - name: Standard library tests
        run: nu -c 'use crates/nu-std/testing.nu; testing run-tests --path crates/nu-std'

      - name: Ensure that Cargo.toml MSRV and rust-toolchain.toml use the same version
        run: nu .github/workflows/check-msrv.nu

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install virtualenv
        run: pip install virtualenv
        shell: bash

      - name: Test Nushell in virtualenv
        run: nu scripts/test_virtualenv.nu
        shell: bash

      - name: Check for clean repo
        shell: bash
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "there are changes";
            git status --porcelain
            exit 1
          else
            echo "no changes in working directory";
          fi
